[package]
name = "system76_firmware_update"
version = "1.0.0"

[lib]
name = "system76_firmware_update"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
rev = "28daccd9159d33fac5e36394e4f9618db8870dc0"
features = ["mem"]

[dependencies]
dmi = { path = "dmi" }
ecflash = { path = "ecflash" }
orbclient = { path = "orbclient" }
plain = "0.2.3"
uefi = { path = "uefi" }
uefi_alloc = { path = "uefi_alloc" }
x86 = "0.7"
