[package]
name = "system76_firmware_setup"
version = "1.0.0"
edition = "2018"

[lib]
name = "system76_firmware_setup"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
coreboot-table = { path = "coreboot-table" }
dmi = { path = "dmi" }
ecflash = { path = "ecflash" }
orbclient = { git = "https://gitlab.redox-os.org/redox-os/orbclient.git", branch = "no_std" }
orbfont = { path = "orbfont", features = ["no_std"] }
plain = "0.2.3"
uefi = { path = "uefi" }
uefi_std = { path = "uefi_std" }
#x86 = "0.7"

[patch."https://gitlab.redox-os.org/redox-os/uefi.git"]
uefi = { path = "uefi" }

[patch."https://gitlab.redox-os.org/redox-os/uefi_alloc.git"]
uefi_alloc = { path = "uefi_alloc" }

[package.metadata.cargo-xbuild]
memcpy = true
sysroot_path = "build/xbuild"
