[package]
name = "system76_firmware_setup"
version = "1.0.0"

[lib]
name = "system76_firmware_setup"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
coreboot-table = { path = "coreboot-table" }
dmi = { path = "dmi" }
ecflash = { path = "ecflash" }
orbclient = { path = "orbclient" }
plain = "0.2.3"
uefi = { path = "uefi" }
uefi_alloc = { path = "uefi_alloc" }
x86 = "0.7"

[package.metadata.cargo-xbuild]
memcpy = true
sysroot_path = "build/xbuild"
